name: C/C++ CI

on:
  push:
    branches: [ "llvm-14.0.6" ]
  pull_request:
    branches: [ "llvm-14.0.6" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: sudo apt install ninja-build -y
      run: sudo apt install ninja-build -y
    - name: git submodule update --remote
      run: git submodule update --remote
    - name: make build
      run: make build
    - name: make install
      run: make install
    - name: make check
      run: make check